#import = ["/home/efrain/.config/alacritty.yml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#9c8d9d"
blue = "#C578C4"
cyan = "#B59BC8"
green = "#976DA5"
magenta = "#605A8D"
red = "#5B4BA3"
white = "#dfcae1"
yellow = "#A270C7"

[colors.cursor]
cursor = "#dfcae1"
text = "#121112"

[colors.normal]
black = "#121112"
blue = "#C578C4"
cyan = "#B59BC8"
green = "#976DA5"
magenta = "#605A8D"
red = "#5B4BA3"
white = "#dfcae1"
yellow = "#A270C7"

[colors.primary]
background = "#000000"
foreground = "#dfcae1"

[env]
TERM = "alacritty"

[font]
size = 9.5

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"


[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 95
lines = 23

[window.padding]
x = 10
y = 10

[window.position]
x = 350
y = 200


